schemaVersion: '0.3'
description: |-
  # Restore Environment
  Runbook Restore-Environment adds NAT Gateways and starts stopped EC2 instances.

  ## Input Parameters
    * **VpcId**: (Required) Id of the target VPC where to create resources.
    * **ProjectTag**: (Optional) Value for the Project tag (default value - 'blog').
    * **EnvironmentTag**: (Optional) Value for the Environment tag (default value - 'dev').
    * **AutomationAssumeRole**: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
assumeRole: '{{ AutomationAssumeRole }}'
parameters:
  VpcId:
    type: String
    description: (Required) Id of the VPC where to create resources.
    allowedPattern: ^vpc-[a-z0-9]{8,17}$
  ProjectTag:
    type: String
    description: (Optional) Value for the Project tag.
    default: blog
  EnvironmentTag:
    type: String
    description: (Optional) Value for the Environment tag.
    default: dev
  AutomationAssumeRole:
    type: AWS::IAM::Role::Arn
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: ^$|arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role\/?[a-zA-Z_0-9+=,.@\-_\/]+
mainSteps:
  - description: Runbook creates Nat Gateway in each public subnet and update private route tables appropriately.
    name: AddNATGateways
    action: aws:executeAutomation
    maxAttempts: 2
    timeoutSeconds: 900
    nextStep: StartEC2Instances
    isEnd: false
    onFailure: Abort
    inputs:
      DocumentName: Add-NATGateways
      RuntimeParameters:
        VpcId: '{{ VpcId }}'
        ProjectTag: '{{ ProjectTag }}'
        EnvironmentTag: '{{ EnvironmentTag }}'
        AutomationAssumeRole: '{{ AutomationAssumeRole }}'
  - description: Runbook starts all stopped EC2 instances in private subnets in the given VPC.
    name: StartEC2Instances
    action: aws:executeAutomation
    maxAttempts: 2
    timeoutSeconds: 600
    isEnd: true
    onFailure: Abort
    inputs:
      DocumentName: Start-EC2Instances
      RuntimeParameters:
        VpcId: '{{ VpcId }}'
        AutomationAssumeRole: '{{ AutomationAssumeRole }}'
